
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action JaxBoxAction;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action EditAction;
	private global::Gtk.Action ViewAction;
	private global::Gtk.Action HelpAction;
	private global::Gtk.Action AboutJaxBoxAction;
	private global::Gtk.Action QuitAction;
	private global::Gtk.Action NewAction;
	private global::Gtk.Action OpenAction;
	private global::Gtk.Action SaveAction;
	private global::Gtk.Action SaveAsAction;
	private global::Gtk.Action CloseAction;
	private global::Gtk.Action UndoAction;
	private global::Gtk.Action RedoAction;
	private global::Gtk.Action CutAction;
	private global::Gtk.Action CopyAction;
	private global::Gtk.Action PasteAction;
	private global::Gtk.Action DeleteAction;
	private global::Gtk.Action DocumentationOnlineAction;
	private global::Gtk.Action SendFeedbackAction;
	private global::Gtk.Action BoxAction1;
	private global::Gtk.Action OrganizerAction;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar menubar1;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.JaxBoxAction = new global::Gtk.Action ("JaxBoxAction", global::Mono.Unix.Catalog.GetString ("JaxBox"), null, null);
		this.JaxBoxAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Jaxbox");
		w1.Add (this.JaxBoxAction, null);
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.EditAction = new global::Gtk.Action ("EditAction", global::Mono.Unix.Catalog.GetString ("Edit"), null, null);
		this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit");
		w1.Add (this.EditAction, null);
		this.ViewAction = new global::Gtk.Action ("ViewAction", global::Mono.Unix.Catalog.GetString ("View"), null, null);
		this.ViewAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("View");
		w1.Add (this.ViewAction, null);
		this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.HelpAction, null);
		this.AboutJaxBoxAction = new global::Gtk.Action ("AboutJaxBoxAction", global::Mono.Unix.Catalog.GetString ("About JaxBox"), null, null);
		this.AboutJaxBoxAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About JaxBox");
		w1.Add (this.AboutJaxBoxAction, null);
		this.QuitAction = new global::Gtk.Action ("QuitAction", global::Mono.Unix.Catalog.GetString ("Quit"), null, null);
		this.QuitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit");
		w1.Add (this.QuitAction, null);
		this.NewAction = new global::Gtk.Action ("NewAction", global::Mono.Unix.Catalog.GetString ("New"), null, null);
		this.NewAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("New");
		w1.Add (this.NewAction, null);
		this.OpenAction = new global::Gtk.Action ("OpenAction", global::Mono.Unix.Catalog.GetString ("Open"), null, null);
		this.OpenAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open");
		w1.Add (this.OpenAction, null);
		this.SaveAction = new global::Gtk.Action ("SaveAction", global::Mono.Unix.Catalog.GetString ("Save"), null, null);
		this.SaveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save");
		w1.Add (this.SaveAction, null);
		this.SaveAsAction = new global::Gtk.Action ("SaveAsAction", global::Mono.Unix.Catalog.GetString ("Save As..."), null, null);
		this.SaveAsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save As...");
		w1.Add (this.SaveAsAction, null);
		this.CloseAction = new global::Gtk.Action ("CloseAction", global::Mono.Unix.Catalog.GetString ("Close"), null, null);
		this.CloseAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Close");
		w1.Add (this.CloseAction, null);
		this.UndoAction = new global::Gtk.Action ("UndoAction", global::Mono.Unix.Catalog.GetString ("Undo"), null, null);
		this.UndoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Undo");
		w1.Add (this.UndoAction, null);
		this.RedoAction = new global::Gtk.Action ("RedoAction", global::Mono.Unix.Catalog.GetString ("Redo"), null, null);
		this.RedoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Redo");
		w1.Add (this.RedoAction, null);
		this.CutAction = new global::Gtk.Action ("CutAction", global::Mono.Unix.Catalog.GetString ("Cut"), null, null);
		this.CutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cut");
		w1.Add (this.CutAction, null);
		this.CopyAction = new global::Gtk.Action ("CopyAction", global::Mono.Unix.Catalog.GetString ("Copy"), null, null);
		this.CopyAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Copy");
		w1.Add (this.CopyAction, null);
		this.PasteAction = new global::Gtk.Action ("PasteAction", global::Mono.Unix.Catalog.GetString ("Paste"), null, null);
		this.PasteAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Paste");
		w1.Add (this.PasteAction, null);
		this.DeleteAction = new global::Gtk.Action ("DeleteAction", global::Mono.Unix.Catalog.GetString ("Delete"), null, null);
		this.DeleteAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Delete");
		w1.Add (this.DeleteAction, null);
		this.DocumentationOnlineAction = new global::Gtk.Action ("DocumentationOnlineAction", global::Mono.Unix.Catalog.GetString ("Documentation (online)"), null, null);
		this.DocumentationOnlineAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Documentation (online)");
		w1.Add (this.DocumentationOnlineAction, null);
		this.SendFeedbackAction = new global::Gtk.Action ("SendFeedbackAction", global::Mono.Unix.Catalog.GetString ("Send Feedback"), null, null);
		this.SendFeedbackAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Send Feedback");
		w1.Add (this.SendFeedbackAction, null);
		this.BoxAction1 = new global::Gtk.Action ("BoxAction1", global::Mono.Unix.Catalog.GetString ("Box"), null, null);
		this.BoxAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Box");
		w1.Add (this.BoxAction1, null);
		this.OrganizerAction = new global::Gtk.Action ("OrganizerAction", global::Mono.Unix.Catalog.GetString ("Organizer"), null, null);
		this.OrganizerAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Organizer");
		w1.Add (this.OrganizerAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='JaxBoxAction' action='JaxBoxAction'><menuitem name='AboutJaxBoxAction' action='AboutJaxBoxAction'/><menuitem name='QuitAction' action='QuitAction'/></menu><menu name='FileAction' action='FileAction'><menu name='NewAction' action='NewAction'><menuitem name='BoxAction1' action='BoxAction1'/><menuitem name='OrganizerAction' action='OrganizerAction'/></menu><menuitem name='OpenAction' action='OpenAction'/><menuitem name='SaveAction' action='SaveAction'/><menuitem name='SaveAsAction' action='SaveAsAction'/><menuitem name='CloseAction' action='CloseAction'/></menu><menu name='EditAction' action='EditAction'><menuitem name='UndoAction' action='UndoAction'/><menuitem name='RedoAction' action='RedoAction'/><menuitem name='CutAction' action='CutAction'/><menuitem name='CopyAction' action='CopyAction'/><menuitem name='PasteAction' action='PasteAction'/><menuitem name='DeleteAction' action='DeleteAction'/></menu><menu name='ViewAction' action='ViewAction'/><menu name='HelpAction' action='HelpAction'><menuitem name='DocumentationOnlineAction' action='DocumentationOnlineAction'/><menuitem name='SendFeedbackAction' action='SendFeedbackAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 497;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.AboutJaxBoxAction.Activated += new global::System.EventHandler (this.OnAbout);
		this.QuitAction.Activated += new global::System.EventHandler (this.OnQuitActionActivated);
		this.OpenAction.Activated += new global::System.EventHandler (this.OnOpenActionActivated);
		this.SaveAction.Activated += new global::System.EventHandler (this.OnSaveActionActivated);
		this.PasteAction.Activated += new global::System.EventHandler (this.OnPasteActionActivated);
	}
}
